name: Quality Gate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  basic-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Basic check
        run: |
          echo "Quality Gate Passed"